### ISSUE TITLE
The warehouse name seems to be hardcoded.

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-spark#101]
When using Soda Spark with Soda Cloud the name looks like its static. This will be an issue for any use case where the data source has the same name:
<img width="1007" alt="Screenshot 2021-12-13 at 15 45 41" src="https://user-images.githubusercontent.com/766412/146782110-16b1cf1d-978e-49f4-8102-7fcb1ae8b36b.png">

**Comment by JCZuurmond** [comment]
It is indeed hard coded [here](https://github.com/sodadata/soda-spark/blob/a62cac1efd3fb765a4b5def704638861c4bfe397/src/sodaspark/scan.py#L239). How would you prefer that the user supplies this? Via the `execute` method, with a field `warehouse_name`?
