### ISSUE TITLE
Unnecessary temporary view in scan.execute?

### ISSUE THREAD

**Issue by wesselklijnsma** [sodadata/soda-spark#108]
When running a scan on a table that is in another database than `default`, the temporary view in `scan.execute` cannot be created because of the prefix in the table name. The scan runs fine without creating this temporary view.

I'm wondering if the creation of a the temporary view in `scan.execute` function is necessary. To the relatively naked eye it seems unnecessary.  Why is it here? Are there situations in which the table is only readable when a temporary view is created in this way?

**Comment by JCZuurmond** [comment]
Hi Wessel, `soda-spark` is intended to run against Spark data frames. If the view/table already exists, I suggest you use [`soda-sql`](https://github.com/sodadata/soda-sql) with the Spark dialect, see [installation guide](https://docs.soda.io/soda-sql/installation.html).

**Comment by wesselklijnsma** [comment]
Thanks, I will check it out
