### ISSUE TITLE
Have scan results as a dataframe

### ISSUE THREAD

**Issue by JCZuurmond** [sodadata/soda-spark#95]
First investigate what the schema of the data frame would look like.

**Comment by anilkulkarni87** [comment]
Currently I have tried converting the `measurements` and `test_result` to a Dataframe. 
https://github.com/anilkulkarni87/databricks_notebooks/blob/main/soda_dq_poc.ipynb

Current Schema based on the how the objects are built in soda:
Measurement: 
```
schema_group_values = T.StructType(
        [
            T.StructField("group", T.StringType(), True),
            T.StructField("value", T.StringType(), True),
        ]
    )
    schema = T.StructType(
        [
            T.StructField("metric", T.StringType(), True),
            T.StructField("columnName", T.StringType(), True),
            T.StructField("value", T.StringType(), True),
            T.StructField("groupValues", schema_group_values, True),
        ]
    )
```

Test_result:
```
schema_group_values = T.StructType(
        [
            T.StructField("expression_result", T.LongType(), True),
            T.StructField("row_count", T.LongType(), True),
        ]
    )    
    schema = StructType([StructField("columnName",T.StringType(),True),
                     StructField("description",T.StringType(),True),
                     StructField("expression",T.StringType(),True),
                     StructField("id",T.StringType(),True),
                     StructField("passed",T.BooleanType(),True),
                     StructField("skipped",T.BooleanType(),True),
                     StructField("title",T.StringType(),True),
                     StructField("values",schema_group_values,True)])
```


Limitation/Drawback: 

- Neither the measurement object nor the test_result object have something as time/run_id to identify when the particular scan was executed.

**Comment by JCZuurmond** [comment]
Hi @anilkulkarni87, thanks for your input!

**Current set-up**
I decided to not return Spark data frames because the [ScanResult](https://github.com/sodadata/soda-sql/blob/6ba9300a292c5ab44a857c0d38f64066bdd5c39e/core/sodasql/scan/scan_result.py#L19) object has some useful methods. 

However, I also see that the data frames are "more natural" to Spark users, it makes sense to have a flow like:

> `dataframe to test` --- `soda testing` --> `data frame with test results`

**New set-up**
The question is: how do we convert the `ScanResults` to data frame(s) **exactly**? 

The `ScanResult` object has three attributes that make sense to convert:
1. `measurements: List[Measurement] = []`
2. `test_results: List[TestResult] = []`
3. `errors: List[ScanError] = []`

These objects are data classes. So we can convert them to a list of tuples with `dataclasses.astuple`. Still, we need to set the schema explicitly, since automatic conversion might break sometimes. For example when the first row contains a `None` where the others contain `bool`s.

I would add the following function to `scan.py`:

``` python
def convert_scan_result_to_spark_data_frames(scan_result: ScanResult) -> tuple[SparkDataFrame, SparkDataFrame, SparkDataframe]:
    """
    Convert the scan results to three Spark data frames.
    
    Parameters
    ------------
    scan_result : ScanResult
        The scan result.
    
    Returns
    --------
    tuple[SparkDataFrame, SparkDataFrame, SparkDataFrame] :
        A Spark data frame with the:
        1. measurements;
        2. test results;
        3. scan errors;
    """
```

Additionally, we can add an [`as_frame`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris) flag to the `scan` function, which is by default `False`, but when set to `True` it will return the output of `convert_scan_result_to_spark_data_frames` instead of the `ScanResult` object.

**Downside of new set-up data frames**
The downside of the new set-up is that `soda-spark` will be more tightly coupled to `soda-sql`. For example, if changes are made to the `ScanResult` then the conversion to data frames might break or miss new attributes.

To be aware about such changes, I would add a test the matches the schema used converting the `Measurement`, `TestResult` and `ScanError` with the fields of those data classes, respectively. If there additional/missing fields in the data classes, then the test should fail.

@anilkulkarni87 : Would you be interested in implementing this issue?

> Neither the measurement object nor the test_result object have something as time/run_id to identify when the particular scan was executed.
This should be [solved in `soda-sql` first](https://github.com/sodadata/soda-sql/issues/588)

**Comment by anilkulkarni87** [comment]
@JCZuurmond. Thank you for putting up an approach for this. Definitely, I am interested to work on this. But Would need more help if i get stuck.

**Comment by anilkulkarni87** [comment]
@JCZuurmond  Do I have permissions to push my branch here?

**Comment by JCZuurmond** [comment]
> @JCZuurmond. Thank you for putting up an approach for this. Definitely, I am interested to work on this. But Would need more help if i get stuck.

Great! You can ask questions in this issue or find me in the Soda slack.

> @JCZuurmond Do I have permissions to push my branch here?

Nope, we do not allow everyone to push to this repo. You should make a [fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks) of this repo first, then push your branch to that fork, and then [create a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by anilkulkarni87** [comment]
I have created a draft pull request now: https://github.com/sodadata/soda-spark/pull/99
Please take a look.
